-- Seed data to match the View Booking page mockup
-- This inserts a booking record with all the details that were previously hardcoded in the page.

INSERT INTO public.bookings (
  "travellerFirstName",
  "travellerLastName",
  "email",
  "phone",
  "passportNumber",
  "passportExpiry",
  "dob",
  "nationality",
  "passportIssueDate",
  "placeOfIssue",
  "origin",
  "destination",
  "travelDate",
  "departureDate",
  "arrivalDate",
  "returnDate",
  "airlines",
  "flightNumber",
  "flightClass",
  "tripType",
  "PNR",
  "ticketNumber",
  "buyingPrice",
  "sellingPrice",
  "currency",
  "status",
  "paymentStatus",
  "paymentMethod",
  "transactionId",
  "dateOfPayment",
  "agency",
  "issuedthroughagency",
  "handledBy",
  "prices"
) VALUES (
  'John',
  'Doe',
  'john.doe@example.com',
  '+1234567890',
  'A1234567X',
  '2029-05-20',
  '1985-03-15',
  'Nepalese',
  '2019-05-20',
  'Kathmandu',
  'SIN',
  'LHR',
  'Wed, 11 Aug 2021',
  'Wed, 11 Aug 2021',
  'Wed, 11 Aug 2021',
  NULL,
  'Singapore Airlines',
  'SQ218',
  'Economy',
  'One Way',
  '68YKCD',
  '784-1234567890',
  '710.00',
  '836.99',
  'USD',
  'Confirmed',
  'Paid',
  'Credit Card',
  'TXN-12345678-ABCD-90',
  '10 Aug 2021',
  'SkyHigh Agency Ltd.',
  'SkyHigh Agency Ltd.',
  'John Doe',
  '{"Meals": 15, "Seat Selection": 25, "Extra Luggage": 45}'::jsonb
);
