-- Seed data to match the View Booking page mockup and Screenshot Booking #21
-- This inserts a booking record with details matching the user's screenshot.

INSERT INTO public.bookings (
  "travellerFirstName",
  "travellerLastName",
  "email",
  "phone",
  "passportNumber",
  "passportExpiry",
  "dob",
  "nationality",
  "passportIssueDate",
  "placeOfIssue",
  "origin",
  "destination",
  "travelDate",
  "departureDate",
  "arrivalDate",
  "returnDate",
  "airlines",
  "flightNumber",
  "flightClass",
  "tripType",
  "PNR",
  "ticketNumber",
  "buyingPrice",
  "sellingPrice",
  "currency",
  "status",
  "paymentStatus",
  "paymentMethod",
  "transactionId",
  "dateOfPayment",
  "agency",
  "issuedthroughagency",
  "handledBy",
  "prices"
) VALUES (
  'POUDEL',
  'SUBEDI',
  'poudel.subedi@example.com',
  '+61400000000',
  'N1234567',
  '2030-01-01',
  '1990-01-01',
  'Nepalese',
  '2020-01-01',
  'Kathmandu',
  'SYD',
  'KTM',
  '15 Nov 2021',
  '15 Nov 2021',
  '16 Nov 2021',
  '15 Dec 2021',
  'SQ',
  'SQ212',
  'Economy',
  'Return',
  '5F8XO2',
  '618-9999999999',
  '1400.00',
  '1520.28',
  'AUD',
  'Confirmed',
  'Paid',
  'Bank Transfer',
  'TXN-99887766',
  '10 Nov 2021',
  'SkyHigh Agency Ltd.',
  'SkyHigh Agency Ltd.',
  'Admin',
  '{"Meals": 0, "Seat": 0}'::jsonb
);
