ALTER TABLE routes
ADD COLUMN IF NOT EXISTS hero_headline TEXT,
ADD COLUMN IF NOT EXISTS hero_subtitle TEXT,
ADD COLUMN IF NOT EXISTS faqs JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS seo_title TEXT,
ADD COLUMN IF NOT EXISTS meta_description TEXT,
ADD COLUMN IF NOT EXISTS slug TEXT,
ADD COLUMN IF NOT EXISTS canonical_url TEXT,
ADD COLUMN IF NOT EXISTS schema_markup TEXT,
ADD COLUMN IF NOT EXISTS robots_meta JSONB DEFAULT '{}'::jsonb;
